### ISSUE TITLE
Harika bir çalışma çok teşekkür ederim.

### ISSUE THREAD

**Issue by UgurSirinTR** [AliAtes/btk-akademi-video-downloader#1]
Buraya başka bir forumdan yönlenerek geldim nasıl kullanıldığını bilmiyorum. Bu nedenle bu şekilde teşekkür etmek istedim. Umarım sorun olmaz. Ellerinize sağlık harika bir çalışma olmuş ve buna çok ihtiyacım vardı. Çok ama çok teşekkür ediyorum.

Sizden bir ricam olsa bu otomatik kurs bitirme çalışması ile ilgili bir projeniz olur mu acaba ?

**Comment by AliAtes** [comment]
teşekkürler, kurs bitirmek için bi çalışmamız yok maalesef.
